[package]
name = "haiku_server"
version = "0.1.0"
authors = ["Eoin Kelly <eoin@rabidtech.co.nz>"]

[dependencies]
hyper = "0.9"
rand = "0.3.15"
rustc-serialize = "0.3.22"
yaml-rust = "*"
lazy_static = "0.2.2"
